controllers/GastosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Gastos;
use app\models\Compras;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\GastosSearch;
use app\models\ObjetivosFinancieros;
use yii\helpers\ArrayHelper;

/**
 * GastosController implements the CRUD actions for Gastos model.
 */
class GastosController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Gastos models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Gastos::find(),
        ]);

        // Consultas para obtener el total de compras de cada mes
        $totalEnero = Gastos::find()->where(['MONTH(fecha)' => 1])->sum('saldo');
        $totalFebrero = Gastos::find()->where(['MONTH(fecha)' => 2])->sum('saldo');
        $totalMarzo = Gastos::find()->where(['MONTH(fecha)' => 3])->sum('saldo');
        $totalAbril = Gastos::find()->where(['MONTH(fecha)' => 4])->sum('saldo');
        $totalMayo = Gastos::find()->where(['MONTH(fecha)' => 5])->sum('saldo');
        $totalJunio = Gastos::find()->where(['MONTH(fecha)' => 6])->sum('saldo');
        $totalJulio = Gastos::find()->where(['MONTH(fecha)' => 7])->sum('saldo');
        $totalAgosto = Gastos::find()->where(['MONTH(fecha)' => 8])->sum('saldo');
        $totalSeptiembre = Gastos::find()->where(['MONTH(fecha)' => 9])->sum('saldo');
        $totalOctubre = Gastos::find()->where(['MONTH(fecha)' => 10])->sum('saldo');
        $totalNoviembre = Gastos::find()->where(['MONTH(fecha)' => 11])->sum('saldo');
        $totalDiciembre = Gastos::find()->where(['MONTH(fecha)' => 12])->sum('saldo');

        // Array con los totales de compras de cada mes
        $datosGrafica = [
            $totalEnero,
            $totalFebrero,
            $totalMarzo,
            $totalAbril,
            $totalMayo,
            $totalJunio,
            $totalJulio,
            $totalAgosto,
            $totalSeptiembre,
            $totalOctubre,
            $totalNoviembre,
            $totalDiciembre,
        ];

        // Llama a la función para obtener los datos del gráfico de objetivos financieros
        $datosObjetivosGrafica = $this->obtenerDatosObjetivosGrafica();
        
        return $this->render('index', [
            'dataProvider' => new ActiveDataProvider([
                'query' => Gastos::find(),
            ]),
            'datosGrafica' => json_encode($datosGrafica), // Convertir el array a JSON
            'datosObjetivosGrafica' => json_encode($datosObjetivosGrafica),
        ]);
    }

    /**
     * Displays a single Gastos model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Gastos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
{
    $model = new Gastos();
    $comprasDisponibles = Compras::find()->select(['concepto', 'id'])->indexBy('id')->column();
    $objetivosFinancieros = Objetivosfinancieros::find()->select(['nombre', 'id'])->indexBy('id')->column();

    if ($model->load(Yii::$app->request->post()) && $model->save()) {
        return $this->redirect(['view', 'id' => $model->id]);
    }

    return $this->render('create', [
        'model' => $model,
        'comprasDisponibles' => $comprasDisponibles,
        'objetivosFinancieros' => $objetivosFinancieros,
    ]);
}


    /**
     * Updates an existing Gastos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Gastos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Gastos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Gastos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Gastos::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Generates a PDF for the Gastos models.
     */
    public function actionPdf()
    {
        $searchModel = new GastosSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $html = $this->renderPartial('pdf_view', ['dataProvider' => $dataProvider]);
        $mpdf = new \Mpdf\Mpdf();
        $mpdf->showImageErrors = true;
        $mpdf->SetDisplayMode('fullpage', 'two');
        $mpdf->list_indent_first_level = 0;
        $mpdf->writeHTML($html);
        $mpdf->Output();
        exit;
    }

    /**
     * Fetch data for financial goals chart.
     * @return array
     */
    protected function obtenerDatosObjetivosGrafica()
    {
        // Obtener los objetivos financieros
        $objetivos = ObjetivosFinancieros::find()->all();

        // Consultar el total de gastos de cada mes, agrupados por objetivos financieros
        $totalGastosPorMes = Gastos::find()
            ->select(['idobjetivofinanciero', 'MONTH(fecha) as mes', 'SUM(saldo) as total'])
            ->groupBy(['idobjetivofinanciero', 'MONTH(fecha)'])
            ->asArray()
            ->all();

        // Crear un array con los datos para la gráfica de objetivos financieros
        $datosGrafica = [];
        foreach ($objetivos as $objetivo) {
            foreach ($totalGastosPorMes as $gasto) {
                if ($gasto['idobjetivofinanciero'] == $objetivo->id) {
                    $datosGrafica[] = [
                        'idobjetivofinanciero' => $objetivo->id,
                        'nombre' => $objetivo->nombre,
                        'mes' => $gasto['mes'],
                        'gasto' => $gasto['total'],
                        'objetivo' => $objetivo->objeto,
                    ];
                }
            }
        }

        return $datosGrafica;
    }
}

controllers/IngresosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Ingresos;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\IngresosSearch;
use app\models\Ventas;
use app\models\ObjetivosFinancieros;
use app\models\Precios;
use yii\helpers\ArrayHelper;

/**
 * IngresosController implements the CRUD actions for Ingresos model.
 */
class IngresosController extends Controller {

    /**
     * @inheritDoc
     */
    public function behaviors() {
        return array_merge(
                parent::behaviors(),
                [
                    'verbs' => [
                        'class' => VerbFilter::className(),
                        'actions' => [
                            'delete' => ['POST'],
                        ],
                    ],
                ]
        );
    }

    /**
     * Lists all Ingresos models.
     *
     * @return string
     */
    public function actionIndex() {
        $dataProvider = new ActiveDataProvider([
            'query' => Ingresos::find(),
        ]);

        // Consultas para obtener el total de compras de cada mes
        $totalEnero = Ingresos::find()->where(['MONTH(fecha)' => 1])->sum('saldo');
        $totalFebrero = Ingresos::find()->where(['MONTH(fecha)' => 2])->sum('saldo');
        $totalMarzo = Ingresos::find()->where(['MONTH(fecha)' => 3])->sum('saldo');
        $totalAbril = Ingresos::find()->where(['MONTH(fecha)' => 4])->sum('saldo');
        $totalMayo = Ingresos::find()->where(['MONTH(fecha)' => 5])->sum('saldo');
        $totalJunio = Ingresos::find()->where(['MONTH(fecha)' => 6])->sum('saldo');
        $totalJulio = Ingresos::find()->where(['MONTH(fecha)' => 7])->sum('saldo');
        $totalAgosto = Ingresos::find()->where(['MONTH(fecha)' => 8])->sum('saldo');
        $totalSeptiembre = Ingresos::find()->where(['MONTH(fecha)' => 9])->sum('saldo');
        $totalOctubre = Ingresos::find()->where(['MONTH(fecha)' => 10])->sum('saldo');
        $totalNoviembre = Ingresos::find()->where(['MONTH(fecha)' => 11])->sum('saldo');
        $totalDiciembre = Ingresos::find()->where(['MONTH(fecha)' => 12])->sum('saldo');

        // Array con los totales de compras de cada mes
        $datosGrafica = [
            $totalEnero,
            $totalFebrero,
            $totalMarzo,
            $totalAbril,
            $totalMayo,
            $totalJunio,
            $totalJulio,
            $totalAgosto,
            $totalSeptiembre,
            $totalOctubre,
            $totalNoviembre,
            $totalDiciembre,
        ];

        return $this->render('index', [
                    'dataProvider' => new ActiveDataProvider([
                        'query' => Ingresos::find(),
                            ]),
                    'datosGrafica' => json_encode($datosGrafica), // Convertir el array a JSON
        ]);

        /*
          $searchModel = new ComprasSearch();
          $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
          return $this->render('index',[
          'searchModel' => $searchModel,
          'dataProvider' => $dataProvider,
          ]);
         * 
         * */
    }

    /**
     * Displays a single Ingresos model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Ingresos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate() {
        $model = new Ingresos();
        $ventasDisponibles = Ventas::getVentasDisponibles(); // Aquí obtienes las ventas disponibles
        // Obtener todos los objetivos financieros disponibles
        $objetivosFinancieros = Objetivosfinancieros::find()->all();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
                    'model' => $model,
                    'ventasDisponibles' => $ventasDisponibles,
                    'objetivosFinancieros' => ArrayHelper::map($objetivosFinancieros, 'id', 'nombre'), // Utiliza ArrayHelper::map para convertir los modelos en un arreglo clave-valor
        ]);
    }

    /**
     * Updates an existing Ingresos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);
        $modelPrecio = Precios::findOne(['idobjetivofinanciero' => $id]);

        // Obtener todos los objetivos financieros disponibles
        $objetivosFinancieros = Objetivosfinancieros::find()->all();

        // Lógica para obtener $ventasDisponibles
        $ventasDisponibles = Ventas::find()->all();
        if ($model->load(Yii::$app->request->post()) && $model->save() && $modelPrecio->load(Yii::$app->request->post()) && $modelPrecio->save()) {
            // Redirige a la ruta deseada
            return $this->redirect(['/compras/create']);
        }



        return $this->render('update', [
                    'model' => $model,
                    'ventasDisponibles' => $ventasDisponibles,
                    'objetivosFinancieros' => $objetivosFinancieros,
        ]);
    }

    /**
     * Deletes an existing Ingresos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Ingresos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Ingresos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Ingresos::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionPdf() {
        $searchModel = new IngresosSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $html = $this->renderPartial('pdf_view', ['dataProvider' => $dataProvider]);
        $mpdf = new \Mpdf\Mpdf();
        $mpdf->showImageErrors = true;
        $mpdf->SetDisplayMode('fullpage', 'two');
        $mpdf->list_indent_first_level = 0;
        $mpdf->writeHTML($html);
        $mpdf->Output();
        exit;
    }

}

views/site/about.php
<?php

/** @var yii\web\View $this */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap4\ActiveForm $form */
/** @var app\models\ContactForm $model */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/** @var yii\web\View $this */
use yii\helpers\Html;
use app\assets\AppAsset;
use yii\helpers\Url;
use app\models\Gastos;
use app\models\Ingresos;

AppAsset::register($this);
$saldototal = $totalVentas - $totalVentas + $totalIngresos - $totalGastos - $totalCompras + $totalCompras;

$this->title = 'My Yii Application';

// Registro de AppAsset
\app\assets\AppAsset::register($this);
?>
<!DOCTYPE html>
<html lang="es">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><?= Html::encode($this->title) ?></title>
        <?= Html::cssFile('@web/css/site.css') ?>
        <link rel="shortcut icon" href="<?= Url::to('@web/logo.ico') ?>" />
        <link rel="icon" type="imagenes/x-icon" href="<?= Url::to('@web/logo.ico') ?>"/>
    </head>

    <body>
        <div class="contenido-principal">
            <!-- IMAGEN DE FONDO -->
            <div class="fondo-pantalla">
                <?=
                Html::img('@web/imagenes/edificio.jpg', [
                    'alt' => 'Edificios - oficinas',
                    'class' => 'img-fluid'
                ])
                ?>
            </div>

            <div class="info-principal hero">
                <h2>Descubre Kumbo</h2>
                <p class="texto-principal">
                    Estamos aquí para ayudarte a alcanzar tus metas financieras. Con nuestras herramientas intuitivas y orientación experta, podrás ahorrar y hacer crecer tu capital de manera fácil y segura.
                    Uniendote a nosotros y comencemos juntos este emocionante viaje hacia un solvente futuro financiero sólido.
                </p>
                <p class="texto-principal">
                    ¡Vamos a empezar a ahorrar y construir juntos!
                </p>

                <!-- Tarjeta de Credito -->
                <div class="card-custom">
                    <div class="card__side-custom card__side_front-custom">
                        <div class="flex__1-custom">
                            <p class="card__side__name-bank-custom">Tarjeta Kumbo</p>
                            <div class="card__side__chip-custom"></div>
                            <p class="card__side__name-person-custom">Kumbo Bank</p>
                            <p class="navbar-text mr-3">XXXXXXXXXXXX €</p>
                        </div>
                    </div>
                    <div class="card__side-custom card__side_back-custom">
                        <div class="card__side__black-custom"></div>
                        <p class="card__side__number">Saldo: /p>
                        <p> </p>
                        <!-- Reemplaza "XXXX XXXX XXXX XXXX" con la consulta de tu saldo -->
                        <?= '<p class="card__side__number-custom">' . Yii::$app->formatter->asCurrency($saldototal) . ' €</p>' ?>
                        <div class="flex__2-custom">
                            <p class="card__side__other-numbers-custom card__side__other-numbers_1-custom"></p>
                            <p class="card__side__other-numbers-custom card__side__other-numbers_2-custom"></p>
                            <div class="card__side__photo-custom"></div>
                            <div class="card__side__debit-custom">Saldo</div>
                        </div>
                        <p class="card__side__other-info-custom">

                        </p>
                    </div>
                </div>

                <p class="card__side__other-info-custom">

                </p>
            </div>
        </div>


    </div>

    <div><!-- comment -->
        <p> </p>
    </div>


    <!-- Contenedor principal para el gráfico y las tarjetas -->
    <div class="contenedor-principal">
        <!-- Canvas para el gráfico -->
        <div class="chart-container">
            <canvas id="myChart"></canvas>
        </div>


        <!-- Contenedor de tarjetas -->
        <div class="contenedor">
            <div class="tarjeta">
                <h2 class="titulo"> Último Objetivo</h2>
                <div class="cuerpo">
                    <?=
                    Html::img(
                            '@web/imagenes/objetivo.png',
                            [
                                'alt' => 'obejivos - objetos',
                                'class' => 'img-fluid '
                            ]
                    );
                    ?>
                    <p>
                        
                    </p>
                    <p>Nombre: <?= $ultimoObjetivo->nombre ?></p>
                    <p>Objeto: <?= $ultimoObjetivo->objeto ?></p>
                </div>
                <?= Html::a('Más información', ['/objetivosfinancieros/index'], ['class' => 'btn btn-primary']) ?>
            </div>

            <div class="tarjeta">
                <h2 class="titulo">Mayor Gasto</h2>
                <div class="cuerpo">
                    <?php
                    $mayorGasto = Gastos::find()->orderBy(['saldo' => SORT_DESC])->limit(1)->one();
                    if ($mayorGasto !== null) :
                        ?>
                        <?=
                        Html::img(
                                '@web/imagenes/iva.png',
                                [
                                    'alt' => 'Mayor Gasto',
                                    'class' => 'img-fluid'
                                ]
                        );
                        ?>
                    <p>
                        
                    </p>
                        <p><?= Yii::$app->formatter->asCurrency($mayorGasto->saldo) ?> €</p>
                    <?php else : ?>
                        <p>No se encontraron gastos.</p>
                    <?php endif; ?>
                </div>
                <?= Html::a('Más información', ['/gastos/index'], ['class' => 'btn btn-primary']) ?>
            </div>
            <div class="tarjeta">
                <h2 class="titulo">Mayor Ingreso</h2>
                <div class="cuerpo">
                    <?php
                    $mayorIngreso = Ingresos::obtenerMayorIngreso();
                    if ($mayorIngreso !== null) :
                        ?>
                        <?=
                        Html::img(
                                '@web/imagenes/venta.png',
                                [
                                    'alt' => 'obejivos - objetos',
                                    'class' => 'img-fluid '
                                ]
                        );
                        ?>
                    <p>
                        
                    </p> <!-- Mostrar detalles del mayor ingreso -->
                        <p><?= Yii::$app->formatter->asCurrency($mayorIngreso->saldo) ?> €</p>
                    <?php else : ?>
                        <p>No se encontraron ingresos.</p>
                    <?php endif; ?>
                         
                </div>
                <?= Html::a('Más información', ['/ingresos/index'], ['class' => 'btn btn-primary']) ?>
            </div>




        </div>
    </div>


    <!-- Script para inicializar el gráfico-->
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const ctx = document.getElementById('myChart').getContext('2d');

            const data = {
                labels: [
                    'Total Ventas',
                    'Total Ingresos',
                    'Total Gastos',
                    'Total Compras'
                ],
                datasets: [{
                        label: 'My First Dataset',
                        data: [<?= $totalVentas ?>, <?= $totalIngresos ?>, <?= $totalGastos ?>, <?= $totalCompras ?>],
                        backgroundColor: [
                            'rgb(46, 204, 113)',
                            'rgb(25, 111, 61)',
                            'rgb(176, 58, 46)',
                            'rgb(231, 76, 60)'
                        ]
                    }]
            };

            const config = {
                type: 'pie',
                data: data,
                options: {
                    responsive: true,
                    plugins: {
                        legend: {
                            position: 'top'
                        },
                        tooltip: {
                            callbacks: {
                                label: function (tooltipItem) {
                                    return tooltipItem.label + ': ' + tooltipItem.raw;
                                }
                            }
                        }
                    }
                }
            };

            new Chart(ctx, config);
        });
    </script>

    <div><!-- comment -->
        <p> </p>
    </div>
</div>
</body>

</html>

views/site/login.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap4\ActiveForm $form */
/** @var app\models\LoginForm $model */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n{input}\n{error}",
            'labelOptions' => ['class' => 'col-lg-1 col-form-label mr-lg-3'],
            'inputOptions' => ['class' => 'col-lg-3 form-control'],
            'errorOptions' => ['class' => 'col-lg-7 invalid-feedback'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"offset-lg-1 col-lg-3 custom-control custom-checkbox\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="offset-lg-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="offset-lg-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>